document sample application

diff --git a/sample/run-sample-app b/sample/run-sample-app
--- a/sample/run-sample-app
+++ b/sample/run-sample-app
@@ -19,30 +19,40 @@ echo "activated mongo_objects sample app virtual environment"
 cat ${SAMPLE_DIR}/requirements.txt | xargs ${VENV_DIR}/bin/pip3 install --disable-pip-version-check
 echo "installed required modules for mongo_objects sample app virtual environment"
 
-# create MongoDB directory if it doesn't exist
-if [ ! -d db ]; then
-    mkdir db
-    echo "created Mongo db directory"
+# if a connection string is provided, log it
+if [[ -n "${MONGO_CONNECT_URI}" ]]; then
+    echo connecting to MongoDB at ${MONGO_CONNECT_URI}
+
+# otherwise, start MongoDB ourselves
+else
+    # create MongoDB directory if it doesn't exist
+    if [ ! -d db ]; then
+        mkdir db
+        echo "created Mongo db directory"
+    fi
+
+    # start MongoDB if it isn't already running
+    if ! mongod --dbpath db > db/mongod-console.out 2>&1 &
+    then
+        echo "unable to start local MongoDB"
+        exit 1
+    fi
+
+    # record MongoDB PID so we can stop it later
+    STARTED_MONGO_PID=$!
+    echo Started MongoDB PID $STARTED_MONGO_PID
 fi
 
-# start MongoDB if it isn't already running
-if ! mongod --dbpath db > db/mongod-console.out 2>&1 &
-then
-    echo "unable to start local MongoDB"
-    exit 1
-fi
-
-# record MongoDB PID so we can stop it later
-STARTED_MONGO_PID=$!
-echo Started MongoDB PID $STARTED_MONGO_PID
-
-# set up environment
+# set up environment for Flask
 export PYTHONPATH=${SAMPLE_DIR}:${SAMPLE_DIR}/../src:$PYTHONPATH
 export FLASK_APP=mongo_objects_sample
 export FLASK_DEBUG=1
 
-# run command, if given, or just start environment
+# start Flask
 flask run --host 127.0.0.1
 
-# shut down MongoDB
-kill -TERM $STARTED_MONGO_PID
+# shut down MongoDB if we started it
+if [[ -z "${MONGO_CONNECT_URI}" ]]; then
+    kill -TERM $STARTED_MONGO_PID
+    echo "Stopped MongoDB"
+fi
